name: CI

on:
  pull_request:

jobs:
  build:
    uses: neotoolkit/.github/.github/workflows/build.yml@main
  dependency:
    uses: neotoolkit/.github/.github/workflows/dependency.yml@main
  lint:
    uses: neotoolkit/.github/.github/workflows/lint.yml@main
